/*
 * MIT License
 *
 * Copyright (c) 2021 Andrew SASSOYE, Constantin GUNDUZ, Gregory VAN DER PLUIJM, Thomas LEUTSCHER
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package esi.acgt.atlj.message.messageTypes;

import esi.acgt.atlj.message.MessageType;
import esi.acgt.atlj.message.ServerMessage;
import esi.acgt.atlj.message.StatisticMessage;
import esi.acgt.atlj.model.player.PlayerStatInterface;

/**
 * Message type to send all game stats generated by client.
 */
public class SendGameStats extends ServerMessage {

  /**
   * Game stats to send.
   */
  private PlayerStatInterface gameStats;

  /**
   * Constructor for sending game statistics.
   *
   * @param gameStats Game Stats interface to send.
   */
  public SendGameStats(PlayerStatInterface gameStats) {
    this.messageType = MessageType.STATISTICS;
    this.gameStats = gameStats;
  }

  /**
   * Getter for gameStats.
   *
   * @return Return game statistics that are sent.
   */
  public PlayerStatInterface getGameStats() {
    return gameStats;
  }

}
